[build-system]
requires = ["briefcase"]

[tool.briefcase]
project_name = "Screenshot Generator"
bundle = "org.beeware.toga.examples"
version = "0.0.1"
url = "https://beeware.org"
license.file = "LICENSE"
author = "Tiberius Yak"
author_email = "tiberius@beeware.org"

formal_name = "Screenshot Generator"
description = "A testing app"
requires = [
    "../../travertino",
    "../../core",
    "pillow",
]

[tool.briefcase.app.screenshot]
sources = ["screenshot"]


[tool.briefcase.app.screenshot-qt]
sources = ["screenshot", "screenshot_qt"]



[tool.briefcase.app.screenshot.macOS]
requires = [
    "../../cocoa",
    "std-nslog>=1.0.0",
]

[tool.briefcase.app.screenshot.linux]
requires = [
    "../../gtk",
]

[tool.briefcase.app.screenshot-qt.linux]
requires = [
    "../../qt",
    "system-pyside6 @ git+https://github.com/johnzhou721/system-pyside6.git"
]

[tool.briefcase.app.screenshot.windows]
requires = [
    "../../winforms",
]

# Mobile deployments
[tool.briefcase.app.screenshot.iOS]
requires = [
    "../../iOS",
    "std-nslog>=1.0.0",
]

[tool.briefcase.app.screenshot.android]
requires = [
    "../../android",
]

base_theme = "Theme.MaterialComponents.Light.DarkActionBar"

build_gradle_dependencies = [
    "com.google.android.material:material:1.12.0",
    "org.osmdroid:osmdroid-android:6.1.20",
]
