
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates on Sunday, 8PM UTC
      interval: "weekly"
      day: "sunday"
      time: "20:00"

  - package-ecosystem: "pip"
    directory: "/toga"
    schedule:
      # Check for updates on Sunday, 8PM UTC
      interval: "weekly"
      day: "sunday"
      time: "20:00"

  - package-ecosystem: "pip"
    directory: "/core"
    schedule:
      # Check for updates on Sunday, 8PM UTC
      interval: "weekly"
      day: "sunday"
      time: "20:00"

  - package-ecosystem: "pip"
    directory: "/android"
    schedule:
      # Check for updates on Sunday, 8PM UTC
      interval: "weekly"
      day: "sunday"
      time: "20:00"

  - package-ecosystem: "pip"
    directory: "/cocoa"
    schedule:
      # Check for updates on Sunday, 8PM UTC
      interval: "weekly"
      day: "sunday"
      time: "20:00"

  - package-ecosystem: "pip"
    directory: "/dummy"
    schedule:
      # Check for updates on Sunday, 8PM UTC
      interval: "weekly"
      day: "sunday"
      time: "20:00"

  - package-ecosystem: "pip"
    directory: "/gtk"
    schedule:
      # Check for updates on Sunday, 8PM UTC
      interval: "weekly"
      day: "sunday"
      time: "20:00"

  - package-ecosystem: "pip"
    directory: "/iOS"
    schedule:
      # Check for updates on Sunday, 8PM UTC
      interval: "weekly"
      day: "sunday"
      time: "20:00"

  - package-ecosystem: "pip"
    directory: "/positron"
    schedule:
      # Check for updates on Sunday, 8PM UTC
      interval: "weekly"
      day: "sunday"
      time: "20:00"

  - package-ecosystem: "pip"
    directory: "/qt"
    schedule:
      # Check for updates on Sunday, 8PM UTC
      interval: "weekly"
      day: "sunday"
      time: "20:00"

  - package-ecosystem: "pip"
    directory: "/testbed"
    ignore:
      # pin PIL for Android and iOS
      - dependency-name: "pillow"
    schedule:
      # Check for updates on Sunday, 8PM UTC
      interval: "weekly"
      day: "sunday"
      time: "20:00"

  - package-ecosystem: "pip"
    directory: "/travertino"
    schedule:
      # Check for updates on Sunday, 8PM UTC
      interval: "weekly"
      day: "sunday"
      time: "20:00"

  - package-ecosystem: "pip"
    directory: "/web"
    schedule:
      # Check for updates on Sunday, 8PM UTC
      interval: "weekly"
      day: "sunday"
      time: "20:00"

  - package-ecosystem: "pip"
    directory: "/winforms"
    schedule:
      # Check for updates on Sunday, 8PM UTC
      interval: "weekly"
      day: "sunday"
      time: "20:00"
