[build-system]
requires = ["briefcase"]

[tool.briefcase]
project_name = "DetailedList Demo"
bundle = "org.beeware"
version = "0.3.0.dev35"
url = "https://beeware.org"
license = "BSD license"
author = 'Tiberius Yak'
author_email = "tiberius@beeware.org"

[tool.briefcase.app.detailedlist]
formal_name = "DetailedList Demo"
description = "A testing app"
sources = ['detailedlist']
requires = [
    '../../src/core',
]


[tool.briefcase.app.detailedlist.macOS]
requires = [
    '../../src/cocoa',
    'std-nslog>=1.0.0',
]

[tool.briefcase.app.detailedlist.linux]
requires = [
    '../../src/gtk',
]

[tool.briefcase.app.detailedlist.windows]
requires = [
    '../../src/winforms',
]

# Mobile deployments
[tool.briefcase.app.detailedlist.iOS]
requires = [
    '../../src/iOS',
    'std-nslog>=1.0.0',
]

[tool.briefcase.app.detailedlist.android]
requires = [
    '../../src/android',
]
