[build-system]
requires = ["briefcase"]

[tool.briefcase]
project_name = "Option Container Example"
bundle = "org.beeware"
version = "0.3.0.dev25"
url = "https://beeware.org"
license = "BSD license"
author = 'Tiberius Yak'
author_email = "tiberius@beeware.org"

[tool.briefcase.app.optioncontainer]
formal_name = "Option Container Example"
description = "A testing app"
sources = ['optioncontainer']
requires = []


[tool.briefcase.app.optioncontainer.macOS]
requires = [
    'toga-cocoa',
]

[tool.briefcase.app.optioncontainer.linux]
requires = [
    'toga-gtk',
]

[tool.briefcase.app.optioncontainer.windows]
requires = [
    'toga-winforms',
]

# Mobile deployments
[tool.briefcase.app.optioncontainer.iOS]
requires = [
    'toga-iOS',
]

[tool.briefcase.app.optioncontainer.android]
requires = [
    'toga-android',
]
