[build-system]
requires = ["briefcase"]

[tool.briefcase]
project_name = "Option Container Example"
bundle = "org.beeware"
version = "0.0.1rc1"
url = "https://beeware.org"
license = "BSD license"
author = 'Tiberius Yak'
author_email = "tiberius@beeware.org"

[tool.briefcase.app.optioncontainer]
formal_name = "Option Container Example"
description = "A testing app"
sources = ['optioncontainer']
requires = [
    '../../src/core',
]


[tool.briefcase.app.optioncontainer.macOS]
requires = [
    '../../src/cocoa',
    'std-nslog>=1.0.0',
]

[tool.briefcase.app.optioncontainer.linux]
requires = [
    '../../src/gtk',
]

[tool.briefcase.app.optioncontainer.windows]
requires = [
    '../../src/winforms',
]

# Mobile deployments
[tool.briefcase.app.optioncontainer.iOS]
requires = [
    '../../src/iOS',
    'std-nslog>=1.0.0',
]

[tool.briefcase.app.optioncontainer.android]
requires = [
    '../../src/android',
]

# Web deployment
[tool.briefcase.app.optioncontainer.web]
requires = [
    '../../src/web',
]
style_framework = "Bootstrap v4.6"
