[build-system]
requires = ["briefcase"]

[tool.briefcase]
project_name = "Date And Time"
bundle = "org.beeware"
version = "0.3.0.dev35"
url = "https://beeware.org"
license = "BSD license"
author = 'Tiberius Yak'
author_email = "tiberius@beeware.org"

[tool.briefcase.app.date_and_time]
formal_name = "Date And Time"
description = "A testing app"
sources = ['date_and_time']
requires = [
    '../../src/core',
]


[tool.briefcase.app.date_and_time.macOS]
requires = [
    '../../src/cocoa',
    'std-nslog>=1.0.0',
]

[tool.briefcase.app.date_and_time.linux]
requires = [
    '../../src/gtk',
]

[tool.briefcase.app.date_and_time.windows]
requires = [
    '../../src/winforms',
]

# Mobile deployments
[tool.briefcase.app.date_and_time.iOS]
requires = [
    '../../src/iOS',
    'std-nslog>=1.0.0',
]

[tool.briefcase.app.date_and_time.android]
requires = [
    '../../src/android',
]
