[build-system]
requires = ["briefcase"]

[tool.briefcase]
project_name = "Command Example"
bundle = "org.beeware"
version = "0.0.1"
url = "https://beeware.org"
license = "BSD license"
author = 'Tiberius Yak'
author_email = "tiberius@beeware.org"

[tool.briefcase.app.command]
formal_name = "Command Example"
description = "A testing app"
sources = ['command']
requires = [
    '../../core',
]


[tool.briefcase.app.command.macOS]
requires = [
    '../../cocoa',
    'std-nslog>=1.0.0',
]

[tool.briefcase.app.command.linux]
requires = [
    '../../gtk',
]

[tool.briefcase.app.command.windows]
requires = [
	'toga-winforms',
]

# Mobile deployments
[tool.briefcase.app.command.iOS]
requires = [
    '../../iOS',
    'std-nslog>=1.0.0',
]

[tool.briefcase.app.command.android]
requires = [
    '../../android',
]

# Web deployment
[tool.briefcase.app.command.web]
requires = [
    '../../web',
]
style_framework = "Shoelace v2.3"
