[build-system]
requires = ["briefcase"]

[tool.briefcase]
project_name = "Document App"
bundle = "org.beeware.toga.examples"
version = "0.0.1"
url = "https://beeware.org"
license.file = "LICENSE"
author = "Tiberius Yak"
author_email = "tiberius@beeware.org"

[tool.briefcase.app.documentapp]
formal_name = "Document App"
description = "A testing app"
sources = ["documentapp"]
requires = [
    "../../core",
    "../../travertino",
]


[tool.briefcase.app.documentapp.macOS]
requires = [
    "../../cocoa",
    "std-nslog>=1.0.0",
]

[tool.briefcase.app.documentapp.linux]
requires = [
    "../../gtk",
]

[tool.briefcase.app.documentapp.windows]
requires = [
    "../../winforms",
]

# Mobile deployments
[tool.briefcase.app.documentapp.iOS]
supported = false

[tool.briefcase.app.documentapp.android]
supported = false

# Web deployment
[tool.briefcase.app.documentapp.web]
supported = false

[tool.briefcase.app.documentapp.document_type.exampledoc]
description = "An example document"
extension = "exampledoc"
icon = "icons/exampledoc"
url = "https://beeware.org"
