[build-system]
requires = ["briefcase"]

[tool.briefcase]
project_name = "WebView Demo"
bundle = "org.beeware.toga.examples"
version = "0.0.1"
url = "https://beeware.org"
license.file = "LICENSE"
author = "Tiberius Yak"
author_email = "tiberius@beeware.org"

[tool.briefcase.app.webview]
formal_name = "WebView Demo"
description = "A demo app using all WebView features"
sources = ["webview"]
requires = [
    "../../travertino",
    "../../core",
]

[tool.briefcase.app.webview.macOS]
requires = [
    "../../cocoa",
    "std-nslog>=1.0.0",
]

[tool.briefcase.app.webview.linux]
requires = [
    "../../gtk",
]

[tool.briefcase.app.webview.windows]
requires = [
    "../../winforms",
]

# Mobile deployments
[tool.briefcase.app.webview.iOS]
requires = [
    "../../iOS",
    "std-nslog>=1.0.0",
]

[tool.briefcase.app.webview.android]
requires = [
    "../../android",
]

base_theme = "Theme.MaterialComponents.Light.DarkActionBar"

build_gradle_dependencies = [
    "com.google.android.material:material:1.12.0",
]

build_gradle_extra_content="""
chaquopy.defaultConfig.staticProxy("toga_android.widgets.internal.webview")
"""

# Web deployment
[tool.briefcase.app.webview.web]
requires = [
    "../../web",
]
style_framework = "Shoelace v2.3"
