[build-system]
requires = ["briefcase"]

[tool.briefcase]
project_name = "Tutorial 3"
bundle = "org.beeware"
version = "0.0.1rc10"
url = "https://beeware.org"
license = "BSD license"
author = 'Tiberius Yak'
author_email = "tiberius@beeware.org"

[tool.briefcase.app.tutorial]
formal_name = "Tutorial 3"
description = "A testing app"
sources = ['tutorial']
requires = [
    '../../core',
]


[tool.briefcase.app.tutorial.macOS]
requires = [
    '../../cocoa',
    'std-nslog>=1.0.0',
]

[tool.briefcase.app.tutorial.linux]
requires = [
    '../../gtk',
]

[tool.briefcase.app.tutorial.windows]
requires = [
    '../../winforms',
]

# Mobile deployments
[tool.briefcase.app.tutorial.iOS]
requires = [
    '../../iOS',
    'std-nslog>=1.0.0',
]

[tool.briefcase.app.tutorial.android]
requires = [
    '../../android',
]

# Web deployment
[tool.briefcase.app.tutorial.web]
requires = [
    '../../web',
]
style_framework = "Bootstrap v4.6"
