[build-system]
requires = ["briefcase"]

[tool.briefcase]
project_name = "TreeSource Demo"
bundle = "org.beeware"
version = "0.3.0.dev25"
url = "https://beeware.org"
license = "BSD license"
author = 'Tiberius Yak'
author_email = "tiberius@beeware.org"

[tool.briefcase.app.tree_source]
formal_name = "TreeSource Demo"
description = "A testing app"
sources = ['tree_source']
requires = []


[tool.briefcase.app.tree_source.macOS]
requires = [
    'toga-cocoa',
]

[tool.briefcase.app.tree_source.linux]
requires = [
    'toga-gtk',
]

[tool.briefcase.app.tree_source.windows]
requires = [
    'toga-winforms',
]

# Mobile deployments
[tool.briefcase.app.tree_source.iOS]
requires = [
    'toga-iOS',
]

[tool.briefcase.app.tree_source.android]
requires = [
    'toga-android',
]
