[build-system]
requires = ["briefcase"]

[tool.briefcase]
project_name = "Text Input Demo"
bundle = "org.beeware"
version = "0.3.0.dev29"
url = "https://beeware.org"
license = "BSD license"
author = 'Tiberius Yak'
author_email = "tiberius@beeware.org"

[tool.briefcase.app.textinput]
formal_name = "Text Input Demo"
description = "A testing app"
sources = ['textinput']
requires = []


[tool.briefcase.app.textinput.macOS]
requires = [
    'toga-cocoa',
]

[tool.briefcase.app.textinput.linux]
requires = [
    'toga-gtk',
]

[tool.briefcase.app.textinput.windows]
requires = [
    'toga-winforms',
]

# Mobile deployments
[tool.briefcase.app.textinput.iOS]
requires = [
    'toga-iOS',
]

[tool.briefcase.app.textinput.android]
requires = [
    'toga-android',
]
