
[tool.briefcase]
project_name = "Toga Demo"
bundle = "org.beeware"
version = "0.3.0.dev35"
url = "https://beeware.org"
license = "BSD license"
author = "Tiberius Yak"
author_email = "tiberius@beeware.org"

[tool.briefcase.app.toga-demo]
formal_name = "Toga Demo"
description = "A demonstration of the capabilities of the Toga widget toolkit."
sources = ["toga_demo"]
requires = []

[tool.briefcase.app.toga-demo.macOS]
requires = [
    "toga-cocoa==0.3.0.dev35",
]

[tool.briefcase.app.toga-demo.linux]
requires = [
    "toga-gtk==0.3.0.dev35",
]

[tool.briefcase.app.toga-demo.windows]
requires = [
    "toga-winforms==0.3.0.dev35",
]

# Mobile deployments
[tool.briefcase.app.toga-demo.iOS]
requires = [
    "toga-iOS==0.3.0.dev35",
]

[tool.briefcase.app.toga-demo.android]
requires = [
    "toga-android==0.3.0.dev35",
]
