[build-system]
requires = ["briefcase"]

[tool.briefcase]
project_name = "Canvas Demo"
bundle = "org.beeware"
version = "0.3.0.dev25"
url = "https://beeware.org"
license = "BSD license"
author = 'Tiberius Yak'
author_email = "tiberius@beeware.org"

[tool.briefcase.app.canvas]
formal_name = "Canvas Demo"
description = "A testing app"
sources = ['canvas']
requires = []


[tool.briefcase.app.canvas.macOS]
requires = [
    'toga-cocoa',
]

[tool.briefcase.app.canvas.linux]
requires = [
    'toga-gtk',
]

[tool.briefcase.app.canvas.windows]
requires = [
    'toga-winforms',
]

# Mobile deployments
[tool.briefcase.app.canvas.iOS]
requires = [
    'toga-iOS',
]

[tool.briefcase.app.canvas.android]
requires = [
    'toga-android',
]
