[build-system]
requires = ["briefcase"]

[tool.briefcase]
project_name = "Layout Test"
bundle = "org.beeware"
version = "0.3.0.dev25"
url = "https://beeware.org"
license = "BSD license"
author = 'Tiberius Yak'
author_email = "tiberius@beeware.org"

[tool.briefcase.app.layout]
formal_name = "Layout Test"
description = "A testing app"
sources = ['layout']
requires = []


[tool.briefcase.app.layout.macOS]
requires = [
    'toga-cocoa',
]

[tool.briefcase.app.layout.linux]
requires = [
    'toga-gtk',
]

[tool.briefcase.app.layout.windows]
requires = [
    'toga-winforms',
]

# Mobile deployments
[tool.briefcase.app.layout.iOS]
requires = [
    'toga-iOS',
]

[tool.briefcase.app.layout.android]
requires = [
    'toga-android',
]
