[build-system]
requires = ["briefcase"]

[tool.briefcase]
project_name = "ImageView Demo"
bundle = "org.beeware.toga.examples"
version = "0.0.1"
url = "https://beeware.org"
license.file = "LICENSE"
author = "Tiberius Yak"
author_email = "tiberius@beeware.org"

[tool.briefcase.app.imageview]
formal_name = "ImageView Demo"
description = "A testing app"
sources = ["imageview"]
requires = [
    "../../travertino",
    "../../core",
]


[tool.briefcase.app.imageview.macOS]
requires = [
    "../../cocoa",
    "std-nslog>=1.0.0",
    "Pillow",
]

[tool.briefcase.app.imageview.linux]
requires = [
    "../../gtk",
    "Pillow",
]

[tool.briefcase.app.imageview.windows]
requires = [
    "../../winforms",
    "Pillow",
]

# Mobile deployments
[tool.briefcase.app.imageview.iOS]
requires = [
    "../../iOS",
    "std-nslog>=1.0.0",
    "Pillow==9.4.0",
]

[tool.briefcase.app.imageview.android]
requires = [
    "../../android",
    "Pillow==9.2.0",
]

base_theme = "Theme.MaterialComponents.Light.DarkActionBar"

build_gradle_dependencies = [
    "com.google.android.material:material:1.12.0",
]

# Web deployment
[tool.briefcase.app.imageview.web]
requires = [
    "../../web",
]
style_framework = "Shoelace v2.3"
