[build-system]
requires = ["briefcase"]

[tool.briefcase]
project_name = "ProgressBar demo"
bundle = "org.beeware"
version = "0.0.1rc1"
url = "https://beeware.org"
license = "BSD license"
author = 'Tiberius Yak'
author_email = "tiberius@beeware.org"

[tool.briefcase.app.progressbar]
formal_name = "ProgressBar demo"
description = "A testing app"
sources = ['progressbar']
requires = [
    '../../src/core',
]


[tool.briefcase.app.progressbar.macOS]
requires = [
    '../../src/cocoa',
    'std-nslog>=1.0.0',
]

[tool.briefcase.app.progressbar.linux]
requires = [
    '../../src/gtk',
]

[tool.briefcase.app.progressbar.windows]
requires = [
    '../../src/winforms',
]

# Mobile deployments
[tool.briefcase.app.progressbar.iOS]
requires = [
    '../../src/iOS',
    'std-nslog>=1.0.0',
]

[tool.briefcase.app.progressbar.android]
requires = [
    '../../src/android',
]

# Web deployment
[tool.briefcase.app.progressbar.web]
requires = [
    '../../src/web',
]
style_framework = "Bootstrap v4.6"
