[build-system]
requires = ["briefcase"]

[tool.briefcase]
project_name = "Divider Demo"
bundle = "org.beeware"
version = "0.0.1"
url = "https://beeware.org"
license = "BSD license"
author = 'Tiberius Yak'
author_email = "tiberius@beeware.org"

[tool.briefcase.app.divider]
formal_name = "Divider Demo"
description = "A testing app"
sources = ['divider']
requires = [
    '../../core',
]


[tool.briefcase.app.divider.macOS]
requires = [
    '../../cocoa',
    'std-nslog>=1.0.0',
]

[tool.briefcase.app.divider.linux]
requires = [
    '../../gtk',
]

[tool.briefcase.app.divider.windows]
requires = [
    '../../winforms',
]

# Mobile deployments
[tool.briefcase.app.divider.iOS]
requires = [
    '../../iOS',
    'std-nslog>=1.0.0',
]

[tool.briefcase.app.divider.android]
requires = [
    '../../android',
]

# Web deployment
[tool.briefcase.app.divider.web]
requires = [
    '../../web',
]
style_framework = "Shoelace v2.3"
