[build-system]
requires = ["briefcase"]

[tool.briefcase]
project_name = "Divider Demo"
bundle = "org.beeware"
version = "0.3.0.dev25"
url = "https://beeware.org"
license = "BSD license"
author = 'Tiberius Yak'
author_email = "tiberius@beeware.org"

[tool.briefcase.app.divider]
formal_name = "Divider Demo"
description = "A testing app"
sources = ['divider']
requires = []


[tool.briefcase.app.divider.macOS]
requires = [
    'toga-cocoa',
]

[tool.briefcase.app.divider.linux]
requires = [
    'toga-gtk',
]

[tool.briefcase.app.divider.windows]
requires = [
    'toga-winforms',
]

# Mobile deployments
[tool.briefcase.app.divider.iOS]
requires = [
    'toga-iOS',
]

[tool.briefcase.app.divider.android]
requires = [
    'toga-android',
]
