[build-system]
requires = ["briefcase"]

[tool.briefcase]
project_name = "Positron"
bundle = "org.beeware"
version = "0.0.1rc1"
url = "https://beeware.org"
license = "BSD license"
author = 'Tiberius Yak'
author_email = "tiberius@beeware.org"

[tool.briefcase.app.positron]
formal_name = "Positron"
description = "Electron, but in Python"
icon = "src/positron/resources/positron"
sources = ['src/positron', 'src/webapp']
requires = [
    '../../src/core',
    'django~=4.1',
]


[tool.briefcase.app.positron.macOS]
requires = [
    '../../src/cocoa',
    'std-nslog>=1.0.0',
]

[tool.briefcase.app.positron.linux]
requires = [
    '../../src/gtk',
]

[tool.briefcase.app.positron.windows]
requires = [
    '../../src/winforms',
]

# Mobile deployments
[tool.briefcase.app.positron.iOS]
requires = [
    '../../src/iOS',
    'std-nslog>=1.0.0',
]

[tool.briefcase.app.positron.android]
requires = [
    '../../src/android',
]

# Web deployment
[tool.briefcase.app.positron.web]
requires = [
    '../../src/web',
]
style_framework = "Bootstrap v4.6"
