name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  docs:
    name: Verify Docs Build
    uses: beeware/.github/.github/workflows/docs-build-verify.yml@main
    secrets: inherit
    with:
      project-name: "toga"
      project-version: ${{ github.ref_name }}

  release:
    name: Create GitHub release
    needs: [ ci, docs ]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set build variables
        run: |
          echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: Get packages
        uses: actions/download-artifact@v4.1.4
        with:
          pattern: ${{ needs.ci.outputs.artifact-name }}-*
          merge-multiple: true

      - name: Create release
        uses: ncipollo/release-action@v1.14.0
        with:
          name: ${{ env.VERSION }}
          draft: true
          artifacts: "*/dist/*"
          artifactErrorsFailBuild: true

  deploy-test:
    name: Publish to TestPyPI
    runs-on: ubuntu-latest
    needs: [ci, release]
    permissions:
      # This permission is required for trusted publishing.
      id-token: write
    strategy:
      matrix:
        package:
        - "toga"
        - "toga_android"
        - "toga_cocoa"
        - "toga_core"
        - "toga_demo"
        - "toga_dummy"
        - "toga_gtk"
        - "toga_iOS"
        - "toga_textual"
        - "toga_web"
        - "toga_winforms"
    steps:
      - name: Get packages
        uses: actions/download-artifact@v4.1.4
        with:
          pattern: ${{ needs.ci.outputs.artifact-name }}-*
          merge-multiple: true

      - name: Extract ${{ matrix.package }}
        run: |
          mkdir dist
          mv */dist/$(echo ${{ matrix.package }} | sed 's/_/?/')-[0-9]* dist

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
